export const ElementTag = {
  BUTTON: "BUTTON",
  LINK: "LINK",
  INPUT_TEXT: "INPUT_TEXT",
  INPUT_SELECT: "INPUT_SELECT",
  INPUT_CHECKBOX: "INPUT_CHECKBOX",
  INPUT_RADIO: "INPUT_RADIO",
  TEXTAREA: "TEXTAREA",
  TOGGLE_SWITCH: "TOGGLE_SWITCH"
};